apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud

    spec:
      volumes:
      - name: nextcloud
        persistentVolumeClaim:
          claimName: nextcloud-pvc

      containers:
      - image: nextcloud
        name: nextcloud
        env:

        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"

        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            configMapKeyRef:
              name: nextcloud-configmap
              key: NEXTCLOUD_ADMIN_USER
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: NEXTCLOUD_ADMIN_PASSWORD
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: nextcloud-configmap
              key: MYSQL_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: nextcloud-configmap
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: nextcloud-configmap
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: MYSQL_PASSWORD

        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /var/www/html
          name: nextcloud

      restartPolicy: Always

---
