apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
type: Opaque
data:
  # echo -n 'YOUR_PASSWORD' | base64
  NEXTCLOUD_ADMIN_PASSWORD: WU9VUl9QQVNTV09SRA==
  MYSQL_PASSWORD: WU9VUl9QQVNTV09SRA==
