---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  labels:
    volume: nextcloud-pv
    app: nextcloud
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kube-data/nextcloud/data"

---
