---

apiVersion: v1
kind: Service
metadata:
  name: homer
  namespace: pro-homer
  labels:
    app: homer
spec:
  ports:
  - port: 8080
  selector:
    app: homer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: pro-homer
spec:
  selector:
    matchLabels:
      app: homer
  replicas: 1
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
      - name: homer
        image: b4bz/homer
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: homer-v
          mountPath: "/www/assets"
      volumes:
      - name: homer-v
        hostPath:
          path: "/home/kube-data/homer/assets"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homer.sysadm.org
  namespace: pro-homer
spec:

  tls:
  - hosts:
    - homer.sysadm.org
    secretName: wildcard.sysadm.org

  rules:
  - host: homer.sysadm.org
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: homer
            port:
              number: 8080
