---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
  labels:
    volume: jellyfin-config-pv
    app: jellyfin
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kube-data/jellyfin/config"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
  labels:
    volume: jellyfin-media-pv
    app: jellyfin
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/kube-data/jellyfin/media"

---
