---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
spec:
  selector:
    matchLabels:
      volume: jellyfin-config-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
spec:
  selector:
    matchLabels:
      volume: jellyfin-media-pv
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  resources:
    requests:
      storage: 20Gi

---
