---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  namespace: pro-transmission
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kube-data/transmission/config"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv
  namespace: pro-transmission
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kube-data/transmission/downloads"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: watch-pv
  namespace: pro-transmission
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kube-data/transmission/watch"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: config-pvc
  name: config-pvc
  namespace: pro-transmission
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: downloads-pvc
  name: downloads-pvc
  namespace: pro-transmission
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: watch-pvc
  name: watch-pvc
  namespace: pro-transmission
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: transmission
  name: transmission
  namespace: pro-transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.service: transmission
    spec:
      containers:
        - env:
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: transmission-secret
                  key: PASS
            - name: HOST_WHITELIST
              value: dnsname list
            - name: PEERPORT
              value: peerport
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TRANSMISSION_WEB_HOME
              value: /
              #value: /combustion-release/
            - name: TZ
              value: Europe/Madrid
            - name: USER
              value: username
            - name: WHITELIST
              value: iplist
          image: lscr.io/linuxserver/transmission:latest
          #image: haugene/transmission-openvpn:2.12
          name: transmission
          ports:
            - containerPort: 9091
            - containerPort: 51413
            - containerPort: 51413
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: config-pvc
            - mountPath: /downloads
              name: downloads-pvc
            - mountPath: /watch
              name: watch-pvc
      restartPolicy: Always
      volumes:
        - name: config-pvc
          persistentVolumeClaim:
            claimName: config-pvc
        - name: downloads-pvc
          persistentVolumeClaim:
            claimName: downloads-pvc
        - name: watch-pvc
          persistentVolumeClaim:
            claimName: watch-pvc

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: transmission
  name: transmission-gui
  namespace: pro-transmission
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    io.kompose.service: transmission

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: transmission
  name: transmission
  namespace: pro-transmission
spec:
  ports:
    - name: "51413"
      port: 51413
      targetPort: 51413
    - name: 51413-udp
      port: 51413
      protocol: UDP
      targetPort: 51413
  selector:
    io.kompose.service: transmission
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  namespace: pro-transmission
spec:
  rules:
  - host: transmission.sysadm.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: transmission-gui
            port:
              number: 9091
  tls:
  - hosts:
    - transmission.sysadm.org
    secretName: wildcard.sysadm.org

---
