---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard-config-pv
  labels:
    volume: wireguard-config-pv
    app: wireguard
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kube-data/wireguard/config"

---
