---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  selector:
    matchLabels:
      app: wireguard
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - env:
            - name: ALLOWEDIPS
              value: 0.0.0.0/0
            - name: INTERNAL_SUBNET
              value: 10.13.13.0
            - name: LOG_CONFS
              value: "true"
            - name: PEERDNS
              value: auto
            - name: PEERS
              value: "1"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: SERVERPORT
              value: "51820"
            - name: SERVERURL
              value: wireguard.sysadm.org
            - name: TZ
              value: Europe/Madrid
          image: lscr.io/linuxserver/wireguard:latest
          name: wireguard
          ports:
            - containerPort: 51820
              protocol: UDP
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          volumeMounts:
            - mountPath: /config
              name: wireguard-config
            - mountPath: /lib/modules
              name: wireguard-modules
      restartPolicy: Always


      volumes:
        - name: wireguard-config
          persistentVolumeClaim:
            claimName: wireguard-config-pvc

        - name: wireguard-modules
          persistentVolumeClaim:
            claimName: wireguard-modules-pvc

---
