---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: desktop-config-pvc
spec:
  selector:
    matchLabels:
      volume: desktop-config-pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
